### ISSUE TITLE
FileHelpers.Dynamic.ClassBuilder.CreateRecordClass Error

### ISSUE THREAD

**Issue by Tabgyn** [MarcosMeli/FileHelpers#193]
I'm trying to reading a file with layout created at runtime. But when running FixedLengthClassBuilder.CreateRecordClass (), an exception occurs: 

```
Error Compiling Expression:
Line 31: The type or namespace name 'SGCompras' could not be found (are you missing a using directive or an assembly reference?).
```

My code:

```C#
public void ReadFile(string filePath){
     ...
     var itemsLayout = Context.FixedLayouts.Where(p => p.LayoutName == "Margem").ToList();
     var builder = GetFixedClass(itemsLayout, "Margem");
     var layout = builder.CreateRecordClass();

     var engine = new FileHelperEngine(layout);
     var linhasArquivo = engine.ReadFile(filePath);
     ...
}

public FixedLengthClassBuilder GetFixedClass(List<FixedLengthLayout> items, string className){
            var cb = new FixedLengthClassBuilder(className);

            foreach (var item in items)
            {
                switch (item.FieldDataType)
                {
                    case "String":
                        cb.AddField(item.FieldName, item.FieldLength, typeof(string));
                        cb.LastField.FieldNullValue = string.Empty;
                        cb.LastField.AlignMode = AlignMode.Left;
                        cb.LastField.AlignChar = ' ';
                        cb.LastField.TrimMode = TrimMode.Both;
                        break;
                    case "Date":
                        cb.AddField(item.FieldName, item.FieldLength, typeof(DateTime));
                        cb.LastField.FieldNullValue = string.Empty;
                        break;
                    case "Custom Date":
                        cb.AddField(item.FieldName, item.FieldLength, typeof(DateTime));
                        cb.LastField.FieldNullValue = string.Empty;
                        cb.LastField.Converter.TypeName = typeof(CustomDateConverter).FullName;
                        cb.LastField.AlignMode = AlignMode.Right;
                        cb.LastField.AlignChar = '0';
                        break;
                    case "Integer":
                        cb.AddField(item.FieldName, item.FieldLength, typeof(int?));
                        cb.LastField.FieldNullValue = 0;
                        cb.LastField.AlignMode = AlignMode.Right;
                        cb.LastField.AlignChar = '0';
                        break;
                    case "Long Integer":
                        cb.AddField(item.FieldName, item.FieldLength, typeof(long?));
                        cb.LastField.FieldNullValue = 0;
                        cb.LastField.AlignMode = AlignMode.Right;
                        cb.LastField.AlignChar = '0';
                        break;
                    case "Decimal":
                        cb.AddField(item.FieldName, item.FieldLength, typeof(decimal?));
                        cb.LastField.FieldNullValue = 0;
                        cb.LastField.AlignMode = AlignMode.Right;
                        cb.LastField.AlignChar = '0';
                        break;
                    case "Custom Decimal":
                        cb.AddField(item.FieldName, item.FieldLength, typeof(decimal?));
                        cb.LastField.FieldNullValue = 0;
                        cb.LastField.Converter.TypeName = typeof(CustomDecimalConverter).FullName;
                        cb.LastField.AlignMode = AlignMode.Right;
                        cb.LastField.AlignChar = '0';
                        break;
                }
            }

            return cb;
        }

public class CustomDateConverter : ConverterBase
    {
        public override object StringToField(string stringValue)
        {
            if (string.IsNullOrEmpty(stringValue) || stringValue == "00000000")
            {
                return null;
            }

            return DateTime.ParseExact(stringValue, "ddMMyyyy", CultureInfo.InvariantCulture);
        }

        public override string FieldToString(object fieldValue)
        {
            return fieldValue == null ? "00000000" : ((DateTime)fieldValue).ToString("ddMMyyyy");
        }
    }

public class CustomDecimalConverter : ConverterBase
    {
        public override object StringToField(string from)
        {
            return Convert.ToDecimal(decimal.Parse(from) / 100);
        }

        public override string FieldToString(object fieldValue)
        {
            return ((decimal)fieldValue).ToString("0.00").Replace(".", "").Replace(",", "");
        }
    }
```

The error relates to my custom converter.

Exception SourceCode

```
[FixedLengthRecord(FixedMode.ExactLength)]
public sealed class Margem
{

[FieldNullValue("")]
[FieldTrim(TrimMode.Both)]
[FieldFixedLength(12)]
public System.String MatriculaCliente;

[FieldNullValue("")]
[FieldTrim(TrimMode.Both)]
[FieldFixedLength(11)]
public System.String CPFCliente;

[FieldNullValue("")]
[FieldTrim(TrimMode.Both)]
[FieldFixedLength(50)]
public System.String NomeCliente;

[FieldNullValue(typeof(System.Int32), "0")]
[FieldFixedLength(2)]
[FieldAlign(AlignMode.Right, '0')]
public System.Nullable<System.Int32> MesReferencia;

[FieldNullValue(typeof(System.Int32), "0")]
[FieldFixedLength(4)]
[FieldAlign(AlignMode.Right, '0')]
public System.Nullable<System.Int32> AnoReferencia;

[FieldNullValue(typeof(System.Int32), "0")]
[FieldConverter(typeof(SGCompras.Nucleo.FileHelper.FileConverters.CustomDecimalConverter))]
[FieldFixedLength(9)]
[FieldAlign(AlignMode.Right, '0')]
public System.Nullable<System.Decimal> ValorMargemFolha;

[FieldNullValue(typeof(System.Int32), "0")]
[FieldConverter(typeof(SGCompras.Nucleo.FileHelper.FileConverters.CustomDecimalConverter))]
[FieldFixedLength(9)]
[FieldAlign(AlignMode.Right, '0')]
public System.Nullable<System.Decimal> ValorMargemCartao;

[FieldNullValue(typeof(System.Int32), "0")]
[FieldConverter(typeof(SGCompras.Nucleo.FileHelper.FileConverters.CustomDecimalConverter))]
[FieldFixedLength(9)]
[FieldAlign(AlignMode.Right, '0')]
public System.Nullable<System.Decimal> ValorDescontoObrigatorio;

[FieldNullValue("")]
[FieldConverter(typeof(SGCompras.Nucleo.FileHelper.FileConverters.CustomDateConverter))]
[FieldFixedLength(8)]
[FieldAlign(AlignMode.Right, '0')]
public System.DateTime DataNascimento;

[FieldNullValue("")]
[FieldConverter(typeof(SGCompras.Nucleo.FileHelper.FileConverters.CustomDateConverter))]
[FieldFixedLength(8)]
[FieldAlign(AlignMode.Right, '0')]
public System.DateTime DataAdmissao;

[FieldNullValue("")]
[FieldConverter(typeof(SGCompras.Nucleo.FileHelper.FileConverters.CustomDateConverter))]
[FieldFixedLength(8)]
[FieldAlign(AlignMode.Right, '0')]
public System.DateTime DataDemissao;

[FieldNullValue(typeof(System.Int32), "0")]
[FieldFixedLength(4)]
[FieldAlign(AlignMode.Right, '0')]
public System.Nullable<System.Int32> RegimeTrabalho;

[FieldNullValue(typeof(System.Int32), "0")]
[FieldFixedLength(3)]
[FieldAlign(AlignMode.Right, '0')]
public System.Nullable<System.Int32> CodigoBanco;

[FieldNullValue("")]
[FieldTrim(TrimMode.Both)]
[FieldFixedLength(10)]
public System.String NumeAgenciaBanco;

[FieldNullValue(typeof(System.Int32), "0")]
[FieldFixedLength(1)]
[FieldAlign(AlignMode.Right, '0')]
public System.Nullable<System.Int32> NumeroDigitoAgencia;

[FieldNullValue("")]
[FieldTrim(TrimMode.Both)]
[FieldFixedLength(12)]
public System.String NumeroContaBanco;

[FieldNullValue(typeof(System.Int32), "0")]
[FieldFixedLength(1)]
[FieldAlign(AlignMode.Right, '0')]
public System.Nullable<System.Int32> NumeroDigitoConta;

[FieldNullValue("")]
[FieldTrim(TrimMode.Both)]
[FieldFixedLength(65)]
public System.String ReservadoEmpresa;

[FieldNullValue("")]
[FieldTrim(TrimMode.Both)]
[FieldFixedLength(10)]
public System.String Critica;

}
```

Exception StackTrace

```
at FileHelpers.Dynamic.ClassBuilder.ClassFromString(String classStr, String className, NetLanguage lang, List`1 additionalReferences)
   at FileHelpers.Dynamic.ClassBuilder.CreateRecordClass()
   at SGCompras.Servicos.ServicoArquivo.ReadFile(String filePath) in D:\Projetos\SGCompras\SGCompras.Servicos\ServicoArquivo.cs:line 356
```

You can view the source code of the exception that FieldConverter was built correctly, as: `[FieldConverter (typeof (SGCompras.Nucleo.FileHelper.FileConverters.CustomDateConverter))]`

Someone would have any idea what might be happening?

**Comment by mcavigelli** [comment]
Hello Tabgyn

Thank you for your detailed report.

It seems that the `FixedLengthClassBuilder` cannot find your own types (`CustomDateConverter` and `CustomDecimalConverter`). The `FixedLengthClassBuilder` generates internally source code (which you have pasted as Exception Source Code). For compiling, it needs assembly references. By default FileHelpers ads some system assemblies and FileHelpers itself.

In your example the generated code references your custom converters. To make them known to the compiler you can add the assembly with the converters to the list `AdditionalReferences` [1].

Adding the assembly with the converters before calling `CreateRecordClass` [2] should solve your problem.

Let me know, if that solved your issue, Matthias

[1] http://www.filehelpers.net/docs/html/P_FileHelpers_Dynamic_ClassBuilder_AdditionalReferences
[2] http://www.filehelpers.net/docs/html/M_FileHelpers_Dynamic_ClassBuilder_CreateRecordClass.htm

**Comment by Tabgyn** [comment]
Tanks Mathias.

My code now:

```
public FixedLengthClassBuilder GetFixedClass(List<FixedLengthLayout> items, string className)
        {
            var cb = new FixedLengthClassBuilder(className);

            foreach (var item in items)
            {
                switch (item.FieldDataType)
                {
                    case "String":
                        cb.AddField(item.FieldName, item.FieldLength, typeof(string));
                        cb.LastField.FieldNullValue = string.Empty;
                        cb.LastField.AlignMode = AlignMode.Left;
                        cb.LastField.AlignChar = ' ';
                        cb.LastField.TrimMode = TrimMode.Both;
                        break;
                    case "Date":
                        cb.AddField(item.FieldName, item.FieldLength, typeof(DateTime));
                        cb.LastField.FieldNullValue = string.Empty;
                        break;
                    case "Custom Date":
                        cb.AddField(item.FieldName, item.FieldLength, typeof(DateTime));
                        //cb.LastField.FieldNullValue = string.Empty;
                        cb.LastField.Converter.TypeName = typeof(CustomDateConverter).FullName;
                        cb.LastField.AlignMode = AlignMode.Right;
                        cb.LastField.AlignChar = '0';
                        break;
                    case "Integer":
                        cb.AddField(item.FieldName, item.FieldLength, typeof(int?));
                        cb.LastField.FieldNullValue = 0;
                        cb.LastField.AlignMode = AlignMode.Right;
                        cb.LastField.AlignChar = '0';
                        break;
                    case "Long Integer":
                        cb.AddField(item.FieldName, item.FieldLength, typeof(long?));
                        cb.LastField.FieldNullValue = 0;
                        cb.LastField.AlignMode = AlignMode.Right;
                        cb.LastField.AlignChar = '0';
                        break;
                    case "Decimal":
                        cb.AddField(item.FieldName, item.FieldLength, typeof(decimal?));
                        cb.LastField.FieldNullValue = 0m;
                        cb.LastField.AlignMode = AlignMode.Right;
                        cb.LastField.AlignChar = '0';
                        break;
                    case "Custom Decimal":
                        cb.AddField(item.FieldName, item.FieldLength, typeof(decimal?));
                        //cb.LastField.FieldNullValue = 0m;
                        cb.LastField.Converter.TypeName = typeof(CustomDecimalConverter).FullName;
                        cb.LastField.AlignMode = AlignMode.Right;
                        cb.LastField.AlignChar = '0';
                        break;
                }
            }

            cb.AdditionalReferences.Add(typeof(CustomDateConverter).Assembly);
            cb.AdditionalReferences.Add(typeof(CustomDecimalConverter).Assembly);

            return cb;
        }
```
